In [1]:
# Base Data Science snippet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import time
from tqdm import tqdm_notebook

%matplotlib inline
%load_ext autoreload
%autoreload 2

# Generating data

Case 1 - OR problem

- Rain -> Wet
- Rain -> not Sprinkler
- Sprinkler -> Wet

Case 2 - XOR problem
Two light buttons to switch on

In [9]:
data = [
    [0,0,0],
    [0,1,1],
    [1,0,1],
]

data = pd.DataFrame(data,columns = ["rain","sprinkler","wet"])
X = data[["rain","sprinkler"]]
y = data["wet"]
data

rain  sprinkler  wet
0     0          0    0
1     0          1    1
2     1          0    1

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

lr = LogisticRegression()
rf = RandomForestClassifier()

In [12]:
lr.fit(X,y)
rf.fit(X,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [18]:
print("-- Classes")
print(lr.predict(X))
print(rf.predict(X))

print("\n-- Probabilities")
print(lr.predict_proba(X))
print(rf.predict_proba(X))

-- Classes
[1 1 1]
[0 1 1]

-- Probabilities
[[0.45383769 0.54616231]
 [0.36566869 0.63433131]
 [0.36566869 0.63433131]]
[[0.7 0.3]
 [0.2 0.8]
 [0.4 0.6]]


In [21]:
print("-- Classes")
print(rf.predict([[1,1]]))

-- Classes
[1]
